Repository gardener/gardenctl-v2, pull requests merged in 2021-07, with the labels that each got.

#27 Add target command tests for seed and shoot
  pkg/cmd/root/completion_test.go
  pkg/cmd/ssh/command.go
  pkg/cmd/ssh/command_test.go
  pkg/cmd/target/command.go
  pkg/cmd/target/command_test.go
  pkg/cmd/target/completion_test.go
  pkg/cmd/target/options.go
Labels: needs/ok-to-test, needs/review, size/m

#29 Upgrade cobra and remove completion command
  go.mod
  go.sum
  pkg/cmd/root/command.go
  pkg/cmd/root/completion.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#31 Add windows build target
  .ci/build
  Makefile
  hack/build-windows-amd64.sh
Labels: needs/ok-to-test, reviewed/lgtm, size/s
