Repository gardener/gardenctl-v2, pull requests merged in 2022-11, with the labels that each got.

#170 change signature options
  pkg/cmd/target/target.go
  pkg/cmd/target/unset.go
  pkg/cmd/target/unset_test.go
  pkg/cmd/target/view.go
  pkg/cmd/target/view_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#176 Enable additional linters
  .golangci.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#172 Add golangci-lint's github action
  .github/workflows/golangci-lint.yml
  .github/workflows/update-gardenctl-v2.yaml
  hack/golangci-lint.sh
Labels: needs/ok-to-test, needs/review, size/s

#175 Add cidr flag completion
  go.mod
  go.sum
  pkg/cmd/ssh/ssh.go
Labels: reviewed/ok-to-test, reviewed/lgtm, size/s
