Repository gardener/gardenctl-v2, pull requests merged in 2023-02, with the labels that each got.

#231 fix: drop no longer relevant TODO/line
  pkg/cmd/sshpatch/options.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#219 [master] Fix help command not working when session id envs not set
  pkg/cmd/cmd_test.go
  pkg/cmd/env/env.go
  pkg/cmd/env/env_test.go
  pkg/cmd/kubeconfig/kubeconfig.go
  pkg/cmd/kubeconfig/kubeconfig_test.go
  pkg/cmd/ssh/ssh.go
  pkg/cmd/ssh/ssh_test.go
  pkg/cmd/sshpatch/sshpatch.go
  pkg/cmd/sshpatch/sshpatch_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#238 [hotfix-2.2] Bump golang from 1.19.5 to 1.19.6
  .ci/pipeline_definitions
  .github/workflows/update-gardenctl-v2.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#222 Bump ginkgo to v2
  go.mod
  go.sum
  internal/gardenclient/client_test.go
  internal/gardenclient/gardenclient_suite_test.go
  internal/util/strings_test.go
  internal/util/util_suite_test.go
  pkg/ac/ac_suite_test.go
  pkg/ac/access_restriction_test.go
  pkg/cmd/base/base_suite_test.go
  pkg/cmd/base/options_test.go
  pkg/cmd/cmd_suite_test.go
  pkg/cmd/cmd_test.go
  pkg/cmd/config/config_suite_test.go
  pkg/cmd/config/config_test.go
  pkg/cmd/config/delete_garden_test.go
  pkg/cmd/config/set_garden_test.go
  pkg/cmd/config/view_test.go
  pkg/cmd/env/env_suite_test.go
  pkg/cmd/env/env_test.go
  pkg/cmd/env/options_test.go
  pkg/cmd/env/rc_test.go
  pkg/cmd/env/shell_test.go
  pkg/cmd/env/template_test.go
  pkg/cmd/kubeconfig/kubeconfig_suite_test.go
  pkg/cmd/kubeconfig/kubeconfig_test.go
  pkg/cmd/ssh/ssh_suite_test.go
  pkg/cmd/ssh/ssh_test.go
  pkg/cmd/sshpatch/sshpatch_suite_test.go
  pkg/cmd/sshpatch/sshpatch_test.go
  pkg/cmd/target/target_suite_test.go
  pkg/cmd/target/target_test.go
  pkg/cmd/target/unset_test.go
  pkg/cmd/target/view_test.go
  pkg/cmd/version/version_suite_test.go
  pkg/cmd/version/version_test.go
  pkg/config/config_suite_test.go
  pkg/config/config_test.go
  pkg/flags/flags_suite_test.go
  pkg/flags/target_test.go
  pkg/target/manager_test.go
  pkg/target/target_flags_test.go
  pkg/target/target_provider_test.go
  pkg/target/target_suite_test.go
  pkg/target/target_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#239 [master] Bump golang from 1.19.5 to 1.19.6
  .ci/pipeline_definitions
  .github/workflows/update-gardenctl-v2.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
