Repository gardener/gardenctl-v2, pull requests merged in 2024-10, with the labels that each got.

#462 Support Namespaced Cloud Profiles
  go.mod
  go.sum
  internal/client/garden/client.go
  internal/client/garden/mocks/mock_client.go
  pkg/cmd/providerenv/export_test.go
  pkg/cmd/providerenv/options.go
  pkg/cmd/providerenv/options_test.go
  pkg/cmd/providerenv/providerenv_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xl, area/ipcei

#464 [GEP-26] Add support for credentials binding
  .gimps.yaml
  internal/client/garden/client.go
  internal/client/garden/mocks/mock_client.go
  main.go
  pkg/cmd/providerenv/options.go
  pkg/cmd/providerenv/options_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/m, area/ipcei

#465 Publish OCM component-descriptor to `gardener-project`
  .ci/pipeline_definitions
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#466 `head-update` job should not overwrite `component_description` trait
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#467 Add ocm repository mappings
  .ci/pipeline_definitions
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#469 Add binaries as release assets to component descriptor
  .ci/build
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/s
