Repository gardener/gardenctl-v2, pull requests merged in 2024-01, with the labels that each got.

#347 ssh - completion with machine objects
  go.mod
  go.sum
  main.go
  pkg/cmd/ssh/options.go
  pkg/cmd/ssh/ssh.go
  pkg/cmd/ssh/ssh_suite_test.go
  pkg/cmd/ssh/ssh_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#369 Set controller-runtime logger
  pkg/cmd/cmd.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#370 Maintenance PR
  .ci/pipeline_definitions
  .github/workflows/update-gardenctl-v2.yaml
  .golangci.yaml
  go.mod
  go.sum
  hack/golangci-lint.sh
  pkg/cmd/ssh/options.go
  pkg/cmd/target/target.go
  pkg/cmd/version/version.go
  pkg/target/target_builder.go
  pkg/target/target_flags.go
  pkg/target/target_provider.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xl

#372 `exe` file ending should be added for windows builds
  hack/build.sh
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#376 [hotfix-2.6] `exe` file ending should be added for windows builds
  hack/build.sh
Labels: reviewed/lgtm, needs/ok-to-test, size/xs
