Repository gardener/gardenctl-v2, pull requests merged in 2025-05, with the labels that each got.

#565 Support ssh to IPv6 addresses.
  pkg/cmd/ssh/arguments.go
  pkg/cmd/ssh/arguments_test.go
  pkg/cmd/ssh/ssh_test.go
Labels: needs/ok-to-test, needs/review, size/xs

#567 Ensure credential type for GCP
  pkg/cmd/providerenv/options.go
  pkg/cmd/providerenv/options_test.go
  pkg/env/testdata/azure/export.json
  pkg/env/testdata/gcp/export.bash
  pkg/env/testdata/gcp/export.seed.bash
  pkg/env/testdata/gcp/export.yaml
  pkg/env/testdata/gcp/serviceaccount.json
  pkg/env/testdata/openstack/export.json
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s

#571 Potential fix for code scanning alert no. 2: Workflow does not contain permissions
  .github/workflows/update-gardenctl-v2.yaml
Labels: reviewed/ok-to-test, needs/review, size/xs

#570 Potential fix for code scanning alert no. 1: Workflow does not contain permissions
  .github/workflows/reuse-tool-lint.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#573 fix "stored" spelling in gardenctl tool
  README.md
  docs/help/gardenctl.md
  pkg/cmd/cmd.go
Labels: needs/ok-to-test, needs/review, size/xs
